// <auto-generated />
using System;
using DatVeXemPhim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatVeXemPhim.Migrations
{
    [DbContext(typeof(DatVeXemPhimContext))]
    [Migration("20240610142439_chien")]
    partial class chien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatVeXemPhim.Models.Ghe", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<int>("maPhong")
                        .HasColumnType("int");

                    b.Property<string>("tenGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.ToTable("Ghe", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.KhachHang", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soDienThoai")
                        .HasColumnType("int");

                    b.Property<string>("taiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.NhanVien", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<string>("diaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("soDienThoai")
                        .HasColumnType("int");

                    b.Property<string>("taiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Phim", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<int>("TheLoaiPhimiD")
                        .HasColumnType("int");

                    b.Property<string>("daoDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dienVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ngonNgu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posterPhim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("theLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("thoiGianKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("thoiLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.HasIndex("TheLoaiPhimiD");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.PhongChieu", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<string>("tenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.TheLoaiPhim", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<string>("tenLoaiPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iD");

                    b.ToTable("TheLoaiPhim", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Ve", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<int>("GheiD")
                        .HasColumnType("int");

                    b.Property<int>("KhachHangiD")
                        .HasColumnType("int");

                    b.Property<int>("NhanVieniD")
                        .HasColumnType("int");

                    b.Property<int>("XuatChieuiD")
                        .HasColumnType("int");

                    b.Property<int>("maGhe")
                        .HasColumnType("int");

                    b.Property<int>("maKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("maNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("maXuatChieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayBanVe")
                        .HasColumnType("datetime2");

                    b.Property<int>("tongTien")
                        .HasColumnType("int");

                    b.HasKey("iD");

                    b.HasIndex("GheiD");

                    b.HasIndex("KhachHangiD");

                    b.HasIndex("NhanVieniD");

                    b.HasIndex("XuatChieuiD");

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.XuatChieu", b =>
                {
                    b.Property<int>("iD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iD"));

                    b.Property<int>("PhimiD")
                        .HasColumnType("int");

                    b.Property<int?>("PhongChieuiD")
                        .HasColumnType("int");

                    b.Property<DateTime>("gioBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("gioKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("maPhim")
                        .HasColumnType("int");

                    b.Property<int>("maPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngayChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("iD");

                    b.HasIndex("PhimiD");

                    b.HasIndex("PhongChieuiD");

                    b.ToTable("XuatChieu", (string)null);
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Phim", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.TheLoaiPhim", "TheLoaiPhim")
                        .WithMany("Phims")
                        .HasForeignKey("TheLoaiPhimiD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheLoaiPhim");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Ve", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Ghe", "Ghe")
                        .WithMany("Ves")
                        .HasForeignKey("GheiD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.KhachHang", "KhachHang")
                        .WithMany("Ves")
                        .HasForeignKey("KhachHangiD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.NhanVien", "NhanVien")
                        .WithMany("Ves")
                        .HasForeignKey("NhanVieniD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.XuatChieu", "XuatChieu")
                        .WithMany("Ves")
                        .HasForeignKey("XuatChieuiD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("XuatChieu");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.XuatChieu", b =>
                {
                    b.HasOne("DatVeXemPhim.Models.Phim", "Phim")
                        .WithMany()
                        .HasForeignKey("PhimiD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatVeXemPhim.Models.PhongChieu", null)
                        .WithMany("XuatChieus")
                        .HasForeignKey("PhongChieuiD");

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.Ghe", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.KhachHang", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.NhanVien", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.PhongChieu", b =>
                {
                    b.Navigation("XuatChieus");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.TheLoaiPhim", b =>
                {
                    b.Navigation("Phims");
                });

            modelBuilder.Entity("DatVeXemPhim.Models.XuatChieu", b =>
                {
                    b.Navigation("Ves");
                });
#pragma warning restore 612, 618
        }
    }
}
